me:
  build: .
  environment:
    SITE_TITLE: 'Lachie' # defaults to 'My OpenSourceMe'
    GITHUB_PATH: 'OpenSourceMe/LachieKermode'
    WEBSITE_FOLDER: 'Website' # defaults to 'Website'
    BRANCH: 'master' # defaults to 'master'
  ports:
   - "3000:3000"